services:
  app:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: ppklj-app
    networks:
      - ppklj
    ports:
      - "9000:80"
    restart: unless-stopped
    depends_on:
      - frontend      
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: unless-stopped
    container_name: ppklj-frontend
    networks:
      - ppklj
    env_file:
      - .env.production
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: .
      dockerfile: ./docker/pocketbase/Dockerfile
    container_name: ppklj-pocketbase
    volumes:
      - ./pb_data:/pb/pb_data
    networks:
      - ppklj

networks:
  ppklj: